### ISSUE TITLE
I can't move the Engineer on Level 3

### ISSUE THREAD

**Issue by GalaxyLJGD** [leveleditor/CrystAlien-Conflict-Flash-Wrapper#1]
I can't move the Engineer to repair the Crystal Miner, he doesn't move when I order him and he can't move anywhere else, but I can move the Infantry and the Crystal Miner, I can even move the engineer on other levels, but for some reason in this one I can't.

![Bug screenshot](https://user-images.githubusercontent.com/11948239/29747199-d3ac54c6-8abe-11e7-90e8-c660b4819f1c.png)

Sorry for my bad English.

**Comment by Brian151** [comment]
hacks over hacks are fun!
especially when it causes a swarm of bugs to appear!
AWESOME!

a bugfix caused bugs...
Well, it's not the first time this has happened...
(probably won't be the last, either)

**Comment by leveleditor** [comment]
I can confirm this is a regression due to a fix added in the last update. I'll try coming up with a solution.

This is the commit that introduced the problem for reference: https://github.com/leveleditor/CrystAlien-Conflict-Flash-Wrapper/commit/aa6821a43c94fadf9f5f2a6b4665ba2e5a7512d6

**Comment by leveleditor** [comment]
This is now fixed. It turns out I forgot to account for a certain edge case in the last fix which caused this to happen. Now that it's accounted for, everything works as intended.

The update should appear on the website sometime later today.

**Comment by Brian151** [comment]
awesome!
I was worried some of our fixes would have to be completely un-done...
